#!/usr/bin/env bash

set -ex

KERL_URL="https://raw.githubusercontent.com/kerl/kerl/master/kerl"

curl -O "$KERL_URL"
chmod +x kerl

Foo=foo.txt
tail -F foo.txt &

yes | head -n 10 >> foo.txt
sleep 10

exit 1
