#!/usr/bin/env bash

set -ex

curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
chmod +x kerl

rm -rf $HOME/.kerl
mkdir -p $HOME/.kerl/builds/master
touch $HOME/.kerl/builds/master/otp_build_git.log
