#!/usr/bin/env bash

BRANCH=$1

if [ -z "$BRANCH" ]; then
    echo "usage: $(basename $0) <branch>"
    exit 1
fi

set -vx

OTP_GITHUB_REPO="https://github.com/erlang/otp.git"

BUILD="$BRANCH-nightly-build"
RELEASE="$BUILD-release"

export KERL_BASE_DIR="$HOME/kerl-nightly"
export KERL_BUILD_DIR="$KERL_BASE_DIR/builds"

LOGFILE="$KERL_BUILD_DIR/$BUILD/otp_build_git.log"

rm -rf "$KERL_BASE_DIR"
mkdir -p $(dirname "$LOGFILE")
touch "$LOGFILE"

{
    echo "Begin tailing..."
    tail -F "$LOGFILE"
    echo "Cease tailing"
} &
TAIL_PID=$!

function cleanup {
    kill $TAIL_PID
}

trap cleanup EXIT

yes | head -20 > $LOGFILE

. ./kerl build git "$OTP_GITHUB_REPO" "$BRANCH" "$BUILD"
. ./kerl install "$BUILD" "$RELEASE"
